Dimension Computation benchmark
DataTorrent/streaming-benchmarks pull request #5
Opened 2016-10-27 16:48 UTC by brightchen

2016-10-27 16:49 UTC, brightchen commented
@vrozov Please review

2016-10-27 17:02 UTC, tweise requested changes

2016-10-27 17:02 UTC, tweise commented on apex-benchmarks/src/main/java/apex/benchmark/ProcessTimeAwareStore.java
> +public class ProcessTimeAwareStore extends AppDataSingleSchemaDimensionStoreHDHT
Please javadoc why this is needed for the benchmark.

2016-10-27 18:30 UTC, vrozov requested changes

2016-10-27 18:30 UTC, vrozov commented on apex-benchmarks/src/main/java/apex/benchmark/ApplicationDimensionComputation.java
> +  protected static class StoreStreamCodec extends KryoSerializableStreamCodec<Aggregate>
Why is KryoSerializableStreamCodec necessary here?

2016-10-27 18:30 UTC, vrozov commented on apex-benchmarks/src/main/java/apex/benchmark/ApplicationDimensionComputation.java
> +    store.setCacheWindowDuration(10000 * 5 / STREAMING_WINDOW_SIZE_MILLIS);   //cache for 5 windows
The number seems odd to me. Is the comment still accurate?

2016-10-27 18:30 UTC, vrozov commented on apex-benchmarks/src/main/java/apex/benchmark/ApplicationDimensionComputation.java
> +//    dag.setAttribute(dimensions, Context.OperatorContext.APPLICATION_WINDOW_COUNT, 120);
Please cleanup

2016-10-27 18:30 UTC, vrozov commented on apex-benchmarks/src/main/java/apex/benchmark/DimensionTuple.java
> +      tuple.campaignId = "1111111111111111111";
Does not look like a valid campaignId.

2016-10-27 18:30 UTC, vrozov commented on apex-benchmarks/src/test/resources/log4j.properties
> +log4j.logger.com.datatorrent=debug
Please review log level settings. DEBUG is good for development and testing. Benchmark should be done with ERROR or at least INFO.

2016-10-27 21:35 UTC, brightchen commented on apex-benchmarks/src/main/java/apex/benchmark/ApplicationDimensionComputation.java
> +    store.setCacheWindowDuration(10000 * 5 / STREAMING_WINDOW_SIZE_MILLIS);   //cache for 5 windows
Our cache will cleaup all when timerout. So it's better to main large duration to decrease the chance of reload data of last window. But too large cache can impact the performance of locating. I choose this number based on some test result.

2016-10-27 21:43 UTC, brightchen commented on apex-benchmarks/src/main/java/apex/benchmark/DimensionTuple.java
> +      tuple.campaignId = "1111111111111111111";
The campaignId should not empty in normal case. 
It used for unit test where campainId will not populated. choose a invalid campainId for easier identify if any problem

2016-10-27 21:44 UTC, brightchen commented on apex-benchmarks/src/test/resources/log4j.properties
> +log4j.logger.com.datatorrent=debug
This is use for unit test

2016-10-28 00:05 UTC, vrozov commented on apex-benchmarks/src/main/java/apex/benchmark/DimensionTuple.java
> +      tuple.campaignId = "1111111111111111111";
Please add comments explaining unit test usage

2016-10-28 00:13 UTC, vrozov commented on apex-benchmarks/src/main/java/apex/benchmark/ApplicationDimensionComputation.java
> +    store.setCacheWindowDuration(10000 * 5 / STREAMING_WINDOW_SIZE_MILLIS);   //cache for 5 windows
It is not caching for 5 windows that will correspond clearing cache every second. The cache seems to be cleared every 13 hours.

2016-10-28 21:27 UTC, brightchen commented on apex-benchmarks/src/main/java/apex/benchmark/ApplicationDimensionComputation.java
> +    store.setCacheWindowDuration(10000 * 5 / STREAMING_WINDOW_SIZE_MILLIS);   //cache for 5 windows
The expiry time is: 10000 * 5 / STREAMING_WINDOW_SIZE_MILLIS * STREAMING_WINDOW_SIZE_MILLIS  = 50000 mill-seconds = 5 application windows

2016-10-28 21:34 UTC, brightchen commented
@vrozov please review

2016-10-28 22:25 UTC, brightchen commented on apex-benchmarks/src/main/java/apex/benchmark/ApplicationDimensionComputation.java
> +    store.setCacheWindowDuration(10000 * 5 / STREAMING_WINDOW_SIZE_MILLIS);   //cache for 5 windows
In the application, the application window in fact same as stream window. The previous application window meant the window of 10 second

2016-10-31 17:53 UTC, merged